### ISSUE TITLE
Doesn't compile on Linux 3.11.0-15

### ISSUE THREAD

**Issue by quux00** [roktas/apue2e#3]
I'm using Xubuntu 13.10 with Linux 3.11.0-15:

```
$ uname -a
Linux cypher 3.11.0-15-generic #23-Ubuntu SMP Mon Dec 9 18:17:04 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
```

and when I try to compile via `make`, I get the error:

```
cc -I/home/midpeter444/media/ebooks/APUE/roktas-apue2e/include -I/home/midpeter444/media/ebooks/APUE/roktas-apue2e/include -DLINUX -DARG_MAX=4611686018427387903 -ansi -Wall -D_GNU_SOURCE -DDEBUG  -c -o printd.o printd.c
In file included from printd.c:6:0:
ipp.h:122:17: error: expected ‘:’, ‘,’, ‘;’, ‘}’ or ‘__attribute__’ before ‘.’ token
 #define status u.st
                 ^
printd.c: In function ‘main’:
printd.c:181:7: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
       (void *)sockfd);
       ^
printd.c: In function ‘client_thread’:
printd.c:405:11: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  sockfd = (int)arg;
           ^
make[2]: *** [printd.o] Error 1
```

I get the same error when I try to compile the code from the apue2e book site.

Any idea how to fix this issue?
